
base_path: '/home/waves/data/Africa_Irrigation'

output_dir: 'Output'

# raw:
Africa_boundaries_shp_path: 'Data/Raw/Africa_Boundaries-shp' # from https://hub.arcgis.com/datasets/07610d73964e4d39ab62c4245d548625/explore
African_Countries_csv_path: 'Data/Raw/african_countries.csv' # just a list of African countries
CPIS_2000_shp_path: 'Data/Raw/World_CPIS-shp/World_CPIS_2000.shp' # from https://github.com/DetectCPIS/global_cpis_shp; see readme for details
CPIS_2021_shp_path: 'Data/Raw/World_CPIS-shp/World_CPIS_2021.shp' # from https://github.com/DetectCPIS/global_cpis_shp; see readme for details
AQUA_World_path: 'Data/Raw/AQUASTAT Dissemination System.csv' # from https://data.apps.fao.org/aquastat/?lang=en; see readme for details

Global_Aridity_Raster_path: 'Data/Raw/Global_Aridity_Map-tif/ai_v3_yr.tif' # from https://figshare.com/articles/dataset/Global_Aridity_Index_and_Potential_Evapotranspiration_ET0_Climate_Database_v2/7504448
Groundwater_Productivity_path: 'Data/Raw/Groundwater_Productivity-txt/xyzASCII_gwprod_v1.txt' # from https://www2.bgs.ac.uk/groundwater/international/africanGroundwater/mapsDownload.html; see README (1) for details
Combined_CPIS_shp_path: 'Data/Raw/Combined_CPIS-shp' # A gift from Anna
Africa_Cropland_tif_path: 'Data/Raw/Africa_Cropland-tif/af_cropland.tif' # from https://sedac.ciesin.columbia.edu/data/set/aglands-croplands-2000/data-download; see README (2) for details

Africa_AEI_2015_asc_path: 'Data/Raw/G_AEI_2015.ASC' # From https://zenodo.org/records/7809342

Global_Dam_Data_csv_path: 'Data/Raw/globaldamsdatabase_global_coverage_november_2020.csv' # from https://sedac.ciesin.columbia.edu/data/set/grand-v1-dams-rev01/maps?facets=region:africa
Global_Dam_Data_shp_path: 'Data/Raw/GDAT_data_v1/data/GDAT_v1_dams.shp' # Retrieved from https://zenodo.org/records/7616852 7/29/24 (alternative dataset)

Africa_Elevation_rast_path: 'Data/Raw/africa_dem' # from https://databasin.org/datasets/2965da954b114ff3b47621e99e3b29ba/
Africa_Countries_shp_path: 'Data/Raw/Africa_Countries-shp' # from https://open.africa/dataset/africa-shapefiles

# Processed:

## Process

### 0_filter_AQUASTAT
AQUA_AfricaIrrigation_2000: 'Data/Processed/AQUA_AfricaIrrigation_2000.csv' # same as AQUASTAT_World_path but filtered to area equipped for irrigation in African countries in 2000
AQUA_AfricaIrrigation_2021: 'Data/Processed/AQUA_AfricaIrrigation_2021.csv' # same as AQUASTAT_World_path but filtered to area equipped for irrigation in African countries in 2021
AQUA_AfricaIrrigation: 'Data/Processed/AQUA_AfricaIrrigation_All.csv' # same as AQUASTAT_World_path but filtered to area equipped for irrigation in Africa
African_Countries_ISO_csv_path: 'Data/Processed/African_Countries_ISO.csv' # African_Countries_csv_path with ISOs added

### 1_CPIS_by_Country
Africa_CPIS_2000_shp_path: 'Data/Processed/Africa_CPIS-shp/Africa_CPIS_2000.shp' # same as CPIS_2000_shp_path but filtered to Africa
Africa_CPIS_2021_shp_path: 'Data/Processed/Africa_CPIS-shp/Africa_CPIS_2021.shp' # same as CPIS_2021_shp_path but filtered to Africa
Africa_CPIS_shp_path: 'Data/Processed/Africa_CPIS-shp/Africa_CPIS.shp' # same as CPIS_2021_shp_path but filtered to Africa

### 2_Aridity_refinement:
Africa_Arid_Regions_tif_path: 'Data/Processed/Africa_Arid_Regions.tif' # Global_Aridity_Raster_path trimmed to the area around africa
Africa_Arid_Regions_tif_path2: 'Data/Processed/Africa_Arid_Regions2.tif' # Global_Aridity_Raster_path trimmed using Africa_boundaries_shp_path
Africa_Arid_Regions_shp_path: 'Data/Processed/Africa_Arid_Regions-shp' # Detailed shapefile from Global_Aridity_Raster_path - did not use

Africa_Continent_shp_path: 'Data/Processed/Africa_Continent-shp/Africa_Continent.shp' # Africa_Boundaries with country borders dissolved

Africa_All_shp_path: 'Data/Processed/Africa_Arid_Regions_All-shp' # Global_Aridity_Raster_path with 1s for all elements < 5000 and 0s otherwise
Africa_Semi_Arid_shp_path: 'Data/Processed/Africa_Semi_Arid-shp' # Africa_all_shp_path filtered to (2000, 5000)
Africa_Arid_shp_path: 'Data/Processed/Africa_Arid-shp' # Africa_all_shp_path filtered to (300, 2000)
Africa_Hyper_Arid_shp_path: 'Data/Processed/Africa_Hyper_Arid-shp/Africa_Hyper_Arid.shp' # Africa_all_shp_path filtered to (0, 300)
#Africa_arid_layered_shp_path: 'Data/Processed/Africa_Layered_Aridity-shp' # Africa_semi_arid_shp_path, Africa_arid_shp_path, and Africa_hyper_arid_shp_path merged

Africa_Arid_by_Country_shp_path: 'Data/Processed/All_Arid_by_Country-shp/All_Arid_by_Country.shp' # Africa_all_shp_path overlayed with Africa_boundaries_shp_path to determine country

### 3_Filter_Cropland
Arid_Cropland_tif_path: 'Data/Processed/Arid_Cropland.tif' # Cropland with aridity < 0.5 with values preserved
Binary_Cropland_tif_path: 'Data/Processed/Cropland_Nonzero_Africa.tif' # Africa_Cropland_tif_path converted to binary, 0 < value = 1
Binary_Arid_Cropland_tif_path: 'Data/Processed/Binary_Arid_Cropland.tif' # Arid_Cropland_tif_path with 1 for cropland and 0 for non-cropland

### 4_CPIS_overlay
Combined_CPIS_Reproj_shp_path: 'Data/Processed/Combined_CPIS_Reprojected-shp/Combined_CPIS_Reprojected.shp' # Combined_CPIS_shp_path reprojected to EPSG:3857

Combined_CPIS_All_shp_path: 'Data/Processed/Combined_CPIS_Aridity_Layers-shp/Combined_CPIS_All.shp' # Combined_CPIS_shp_path filtered to arid boundary
Combined_CPIS_Semi_Arid_shp_path: 'Data/Processed/Combined_CPIS_Aridity_Layers-shp/Combined_CPIS_Semi_Arid.shp' # Combined_CPIS_shp_path filtered to arid boundary
Combined_CPIS_Arid_shp_path: 'Data/Processed/Combined_CPIS_Aridity_Layers-shp/Combined_CPIS_Arid.shp' # Combined_CPIS_shp_path filtered to arid boundary
Combined_CPIS_Hyper_Arid_shp_path: 'Data/Processed/Combined_CPIS_Aridity_Layers-shp/Combined_CPIS_Hyper_Arid.shp' # Combined_CPIS_shp_path filtered to arid boundary


### 5_Dam_processing
Africa_Dam_csv_path: 'Data/Processed/Africa_Dams.csv' # Global_Dam_Data_csv_path filtered to only africa
Africa_Dam_Irrigation_csv_path: 'Data/Processed/Africa_Dams_Irrigation.csv' # Africa_Dam_csv_path filtered to dams that have 'Irrigation' listed under 'purpose'
Africa_Dam_Irrigation_Only_csv_path: 'Data/Processed/Africa_Dams_Irrigation_Only.csv' # Africa_Dam_csv_path filtered to dams that ONLY have 'Irrigation' listed under 'purpose'
Africa_Dam_All_shp_path: 'Data/Processed/Africa_Dam_Aridity_Layers-shp/Africa_Dam_All_Arid.shp' # Africa_Dam_csv_path trimmed to all arid regions
Africa_Dam_Semi_Arid_shp_path: 'Data/Processed/Africa_Dam_Aridity_Layers-shp/Africa_Dam_Semi_Arid.shp' # Africa_Dam_csv_path trimmed to semi arid regions
Africa_Dam_Arid_shp_path: 'Data/Processed/Africa_Dam_Aridity_Layers-shp/Africa_Dam_Arid.shp' # Africa_Dam_csv_path trimmed to arid regions
Africa_Dam_Hyper_Arid_shp_path: 'Data/Processed/Africa_Dam_Aridity_Layers-shp/Africa_Dam_Hyper_Arid.shp' # Africa_Dam_csv_path trimmed to hyper arid regions

### 6_AEI_trimming
AEI_2015_cropped_tif_path: 'Data/Processed/G_AEI_2015_Cropped.tif' # Cropped to Africa
AEI_2015_reproj_gpkg_path: 'Data/Processed/G_AEI_2015_Reprojected.gpkg' # Africa_AEI_2015_asc_path cropped to Africa and reprojected to EPSG:3857

AEI_2015_All_shp_path: 'Data/Processed/G_AEI_2015_Aridity_Layers-shp/G_AEI_2015_All_Arid.shp' # AEI_2015_reproj_gpkg_path cropped by Africa_All_shp_path
AEI_2015_Semi_Arid_shp_path: 'Data/Processed/G_AEI_2015_Aridity_Layers-shp/G_AEI_2015_Semi_Arid.shp' # AEI_2015_reproj_gpkg_path cropped by Africa_Semi_Arid_shp_path
AEI_2015_Hyper_Arid_shp_path: 'Data/Processed/G_AEI_2015_Aridity_Layers-shp/G_AEI_2015_Hyper_Arid.shp' # AEI_2015_reproj_gpkg_path cropped by Africa_Hyper_Arid_shp_path
AEI_2015_Arid_shp_path: 'Data/Processed/G_AEI_2015_Aridity_Layers-shp/G_AEI_2015_Arid.shp' # AEI_2015_reproj_gpkg_path cropped by Africa_Arid_shp_path


## Analyze

### 0_CPIS_vs_Total
Africa_CPIS_2000_Areas_path: 'Data/Processed/Africa_CPIS_2000_Areas.csv' # from Africa_CPIS_2000.shp, areas of CPIS and their locations and total area in Africa
Africa_CPIS_2021_Areas_path: 'Data/Processed/Africa_CPIS_2021_Areas.csv' # from Africa_CPIS_2021.shp, areas of CPIS and their locations and total area in Africa
Africa_CPIS_Areas_path: 'Data/Processed/Africa_CPIS_Areas.csv' # 2000 and 2021 merged

### 1_CPIS_Africa_Map
CPIS_Area_by_Country_2000_path: 'Data/Processed/Africa_CPIS_2000_Area_By_Country.csv' # from Africa_CPIS_2000.shp, total area of CPIS per country
CPIS_Area_by_Country_2021_path: 'Data/Processed/Africa_CPIS_2021_Area_By_Country.csv' # from Africa_CPIS_2021.shp, total area of CPIS per country
Comp_by_Country_2000_path: 'Data/Processed/Percent_CPIS_by_Country_2000.csv' # area of all irrigation and of CPIS per country and % (CPIS area / total irrigated area) per country in 2000
Comp_by_Country_2021_path: 'Data/Processed/Percent_CPIS_by_Country_2021.csv' # area of all irrigation and of CPIS per country and % (CPIS area / total irrigated area) per country in 2021

Merged_Areas_2000: 'Data/Processed/Merged_Area_Data_2000.shp' # Percent_CPIS_by_Country_2000.csv merged with Africa_Boundaries.shp, used to make Fig2

### 3_Groundwater:
Groundwater_Prod_gpkg_path: 'Data/Processed/Groundwater_Prod.gpkg' # Groundwater_Productivity_path .txt file made into geopackage
Groundwater_Prod_Arid_Cropland_gpkg_path: 'Data/Processed/Groundwater_Prod_Arid_Cropland.gpkg' # Groundwater_Prod_gpkg_path filtered to arid cropland 
CPIS_Groundwater_Prod_gpkg_path: 'Data/Processed/CPIS_Groundwater_Prod.gpkg' # Groundwater_Prod_gpkg_path filtered to CPIS

### 4_Dams_AEI/Cropland:
#Africa_Dam_Reproj_shp_path: 'Data/Processed/Africa_Dams_Reprojected-shp/Dams_Reprojected.shp' # Africa_Dam_csv_path reprojected to EPSG:3857

Dam_All_by_Country_shp_path: 'Data/Processed/Africa_Dam_by_Country-shp/Africa_All_Dam_by_Country.shp' # Africa_Dam_ReProj_shp_path including only reprojected geometries and from Africa_Dam_ReProj_shp_path and ISO3 values from Africa_Countries_Reproj_shp_path
Dam_Semi_Arid_by_Country_shp_path: 'Data/Processed/Africa_Dam_by_Country-shp/Africa_Semi_Arid_Dam_by_Country.shp' # Africa_Dam_ReProj_shp_path including only reprojected geometries and from Africa_Dam_ReProj_shp_path and ISO3 values from Africa_Countries_Reproj_shp_path
Dam_Arid_by_Country_shp_path: 'Data/Processed/Africa_Dam_by_Country-shp/Africa_Arid_Dam_by_Country.shp' # Africa_Dam_ReProj_shp_path including only reprojected geometries and from Africa_Dam_ReProj_shp_path and ISO3 values from Africa_Countries_Reproj_shp_path
Dam_Hyper_Arid_by_Country_shp_path: 'Data/Processed/Africa_Dam_by_Country-shp/Africa_Hyper_Arid_Dam_by_Country.shp' # Africa_Dam_ReProj_shp_path including only reprojected geometries and from Africa_Dam_ReProj_shp_path and ISO3 values from Africa_Countries_Reproj_shp_path

Arid_Cropland_Reproj_tif_path: 'Data/Processed/Arid_Cropland_Reproj.tif' # Arid_Cropland_tif_path reprojected to EPSG:3857
Arid_Cropland_by_Country_shp_path: 'Data/Processed/Arid_Cropland_by_Country-shp/Arid_Cropland_by_Country.shp' # Arid_Cropland_Reproj_tif_path data by country using Africa_Countries_Reproj_shp_path

Combined_CPIS_All_by_Country_shp_path: 'Data/Processed/Combined_CPIS_by_Country-shp/Combined_CPIS_All_by_Country.shp' # Combined_CPIS_All_shp_path data by country using Africa_Countries_Reproj_shp_path
Combined_CPIS_Semi_Arid_by_Country_shp_path: 'Data/Processed/Combined_CPIS_by_Country-shp/Combined_CPIS_Semi_Arid_by_Country.shp' # Combined_CPIS_Semi_Arid_shp_path data by country using Africa_Countries_Reproj_shp_path
Combined_CPIS_Arid_by_Country_shp_path: 'Data/Processed/Combined_CPIS_by_Country-shp/Combined_CPIS_Arid_by_Country.shp' # Combined_CPIS_Arid_shp_path data by country using Africa_Countries_Reproj_shp_path
Combined_CPIS_Hyper_Arid_by_Country_shp_path: 'Data/Processed/Combined_CPIS_by_Country-shp/Combined_CPIS_Hyper_Arid_by_Country.shp' # Combined_CPIS_Hyper_Arid_shp_path data by country using Africa_Countries_Reproj_shp_path


AEI_2015_by_Country_All_shp_path: 'Data/Processed/G_AEI_2015_by_Country-shp/G_AEI_2015_All_by_Country.shp' # All_AEI_2015_shp_path data by country using Africa_Countries_Reproj_shp_path
AEI_2015_by_Country_Semi_Arid_shp_path: 'Data/Processed/G_AEI_2015_by_Country-shp/G_AEI_2015_Semi_Arid_by_Country.shp' # Semi_Arid_AEI_2015_shp_path data by country using Africa_Countries_Reproj_shp_path
AEI_2015_by_Country_Arid_shp_path: 'Data/Processed/G_AEI_2015_by_Country-shp/G_AEI_2015_Arid_by_Country.shp' # Arid_AEI_2015_shp_path data by country using Africa_Countries_Reproj_shp_path
AEI_2015_by_Country_Hyper_Arid_shp_path: 'Data/Processed/G_AEI_2015_by_Country-shp/G_AEI_2015_Hyper_Arid_by_Country.shp' # Hyper_Arid_AEI_2015_shp_path data by country using Africa_Countries_Reproj_shp_path

Africa_Countries_Reproj_shp_path: 'Data/Processed/Africa_Countries_Reprojected-shp/Africa_Countries_Reprojected.shp' # Africa_Countries_shp_path reprojected to EPSG:3857


Africa_Elevation_Reprojected_tif_path: 'Data/Processed/Africa_Elevation_Reprojected.tif' # Africa_Elevation_rast_path reprojected to EPSG:3857 


#Dams_with_Gradients_gpkg_path: 'Data/Processed/Dam_Gradients.gpkg' # Africa_Dam_csv_path with gradient direction
#CPIS_Classified_gpkg_path: 'Data/Processed/Classified_CPIS.gpkg' # Combined_CPIS_shp_path with 'upstream'/'downstream' classification


