name: irrigation
channels:
  - conda-forge
dependencies:
  - python=3.12
  - gdal
  - numpy
  - geopandas==0.14.4
  - shapely
  - fiona
  - matplotlib
  - folium
  - pyproj
  - rasterio
  - descartes
  - requests
  - pandas
  - affine
  - pip
  - pip:
    - pyyaml==6.0.1
    - ipykernel==6.29.3
